"""Build the website's data file from the weather CSVs.

Reads each location's CSV, normalizes the columns, aligns every date onto a
fixed 365-day calendar (so leap years line up), and writes the result to
docs/data.js as `window.WEATHER_DATA`.

Using a .js file (instead of .json fetched at runtime) means the site works
both on GitHub Pages and when opened locally as a file:// page, with no CORS
or local-server requirement.

Run:  python build_data.py
"""

import calendar
import csv
import glob
import json
import os
from collections import defaultdict
from datetime import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(HERE, "docs", "data.js")
REGISTRY = os.path.join(HERE, "locations.json")

# locations.json maps a slug -> display name. The CSV for a slug is found by
# globbing "<slug>_weather*.csv". Add a location by running get_weather_data.py
# (which fetches the CSV and updates locations.json for you).


def csv_for_slug(slug):
    """Return the CSV path for a slug, or None if no file matches.

    If several match (e.g. different year ranges), the last by name wins, which
    is the newest year range.
    """
    matches = sorted(glob.glob(os.path.join(HERE, slug + "_weather*.csv")))
    return matches[-1] if matches else None


def to_float(value):
    """Safely convert a CSV value to float, or None if blank/invalid."""
    try:
        if value is None or value == "":
            return None
        return float(value)
    except (ValueError, TypeError):
        return None


def first_float(row, keys):
    """Return the first valid float in `row` among the candidate column names."""
    for key in keys:
        if key in row:
            value = to_float(row[key])
            if value is not None:
                return value
    return None


def ref_day_index(dt):
    """Map a date onto a fixed 365-day calendar (1-365).

    In leap years, March 1 onward is shifted back by one day and Feb 29 folds
    onto Feb 28, so the same calendar day lands on the same x position every
    year.
    """
    doy = dt.timetuple().tm_yday
    if calendar.isleap(dt.year) and doy >= 60:  # Feb 29 and everything after
        doy -= 1
    return doy


def load_location(csv_path):
    """Return {"years": [...], "data": {year: [{d, lo, hi, avg}, ...]}}."""
    # per_year[year][day_index] = (lo_sum, hi_sum, avg_sum, count) for averaging
    # collisions (Feb 28/29 fold onto the same index in leap years).
    per_year = defaultdict(lambda: defaultdict(lambda: [0.0, 0.0, 0.0, 0]))

    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                dt = datetime.strptime(row.get("date", ""), "%Y-%m-%d")
            except ValueError:
                continue

            lo = first_float(row, ["tempmin_f", "tempmin"])
            hi = first_float(row, ["tempmax_f", "tempmax"])
            avg = first_float(row, ["tempavg_f", "tempavg"])
            if lo is None or hi is None or avg is None:
                continue

            d = ref_day_index(dt)
            acc = per_year[dt.year][d]
            acc[0] += lo
            acc[1] += hi
            acc[2] += avg
            acc[3] += 1

    data = {}
    for year, days in per_year.items():
        series = []
        for d in sorted(days):
            lo_sum, hi_sum, avg_sum, count = days[d]
            series.append({
                "d": d,
                "lo": round(lo_sum / count, 1),
                "hi": round(hi_sum / count, 1),
                "avg": round(avg_sum / count, 1),
            })
        data[str(year)] = series

    return {"years": sorted(per_year.keys()), "data": data}


def main():
    with open(REGISTRY) as f:
        registry = json.load(f)

    locations = {}
    for slug, name in registry.items():
        path = csv_for_slug(slug)
        if path is None:
            print(f"  skip (no CSV for slug '{slug}')")
            continue
        locations[slug] = {"name": name, **load_location(path)}
        years = locations[slug]["years"]
        print(f"  loaded {name}: {years}")

    payload = {"locations": locations}
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write("// Auto-generated by build_data.py - do not edit by hand.\n")
        f.write("window.WEATHER_DATA = ")
        json.dump(payload, f, separators=(",", ":"))
        f.write(";\n")

    print(f"Wrote {OUTPUT} ({len(locations)} locations)")


if __name__ == "__main__":
    main()
